export const FETCH_CONFIGS_REQUEST = 'FETCH_CONFIGS_REQUEST'
export const FETCH_CONFIGS_SUCCESS = 'FETCH_CONFIGS_SUCCESS'
export const FETCH_CONFIGS_FAILURE = 'FETCH_CONFIGS_FAILURE'
export const CREATE_CONFIG = 'CREATE_CONFIG'
