export const FETCH_APPOINTMENTS_REQUEST = 'FETCH_APPOINTMENTS_REQUEST'
export const FETCH_APPOINTMENTS_SUCCESS = 'FETCH_APPOINTMENTS_SUCCESS'
export const FETCH_APPOINTMENTS_FAILURE = 'FETCH_APPOINTMENTS_FAILURE'

export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT'
export const READ_APPOINTMENT = 'READ_APPOINTMENT'
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT'
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT'